version: '3.8'
services:
  nginx: # nginx 
    image: nginx:stable-alpine
    ports:
      - "3000:80" # "extarnal:nginx"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app: #container name
    build: . # Dockerfile location
    # ports: # not needed when nginx added
    #   - "3000:3000" # extarnal:internal ports
    #   - "3000-3001:3000" # from-extarnal-to-extarnal:internal ports
    environment:
      - PORT=3000
    depends_on: # first start these services because I(node-app) depends_on them
    # it just start mongo first and then node-app
    # but docker hav no idea that mongo is ready to listening
    # so we need to write some logic to solve this issue
      - mongo 
  
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo-db:/data/db # named volume name:annonymous volumes
  
  redis:
    image: redis


volumes: # for name volumes 
  mongo-db: