version: '3.8'
services:
  node-app: #container name
    build: . # Dockerfile location
    ports:
      - "3000:3000" # extarnal:internal ports
    environment:
      - PORT=3000
  
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo-db:/data/db


volumes:
  mongo-db: