version: '3.8'
services:
  nginx: # nginx 
    image: nginx:stable-alpine
    ports:
      - "80:80" # "extarnal:nginx"
  node-app:
    build:
      context: . # Dockerfile location
      args: # Dockerfile arguments
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node index.js