version: '3.8'
services:
  node-app: #container name
    build: . # Dockerfile location
    ports:
      - "3000:3000" # extarnal:internal ports
    environment:
      - PORT=3000
    depends_on: # first start these services because I depends_on them
    # it just start mongo first and then node-app
    # but docker hav no idea that mongo is ready to listening
    # so we need to write some logic to solve this issue
      - mongo 
  
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo-db:/data/db # named volume name:annonymous volumes


volumes: # for name volumes 
  mongo-db: